#!/bin/bash
git add -A
git add .                                                                                  




q_marks='"'                                                                                




echo "Commit message;"                                                                     

read message                                                                               




git commit -m $q_marks"$message"$q_marks                                                   

git push                                                                                   

git status

